name: Build and deploy  Angular application

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Fetching the code
              uses: actions/checkout@v4
            
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                 node-version: '20'

            - name: Install dependencies
              run: npm ci

            - name: Building the application
              run: npm run build
            
            - name: upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: drop
                path: dist/my_app