name: Actions Demo
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout@master
        uses: actions/checkout@v4

      - name: Use node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
      
      - name: Building the app
        run: npm run build 

      - name: Publish artifacts
        uses: actions/upload-artifacts@v4
        with:
          name: drop
          path: dist/my_app
  

  
