name: Build angular application

on:
    push: 
    workflow_dispatch:

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Install necessary dependencies
              run: npm ci
            - name: Build the app
              run: npm run build
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: drop
                path: dist/
    deploy:
      needs: Build
      environment: prod
      runs-on: ubuntu-latest
      steps:
          - name: downloadig the artifacts
            uses: actions/download-artifact@v4
            with:
                name: drop      
          - name: powershell task
            shell: pwsh
            run: Write-Output "Hello How are you?"