name: Angular build and deploy

on: 
    workflow_dispatch:
    push:

jobs:
    Build-app:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out the  code
              uses:  actions/checkout@v4

            - name: Use node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            
            - name: Install dependencies
              run: npm ci

            - name: Build application
              run: npm run build

            - name: Publish artifacts
              uses: actions/upload-artifact@v4
              with:
                name: drop
                path: dist/my_app
            