name: Deploy angular application

on:
    workflow_run: 
        workflows: ['Build angular application']
        types:
            - completed

jobs:
    Build:
        environment: prod
        runs-on: ubuntu-latest
        steps:
            - name: downloadig the artifacts
              uses: actions/download-artifact@v4
              with:
                name: drop
              