name: Deploy angular application

on:
    workflow_run: 
        workflows: ['Build angular application']
        types:
            - completed

jobs:
    Deployment:
        environment: prod
        runs-on: self-hosted
        steps:
            - name: Downloadig the artifacts
              uses: actions/download-artifact@v4
              with:
                name: drop
                repository: ${{github.repository}}
                run-id: 13114236398
                github-token: ${{github.token}}
              