name: Deploy angular application

on:
    workflow_run: 
        workflows: ['Build angular application']
        types:
            - completed

jobs:
    Deployment:
        environment: prod
        runs-on: self-hosted
        steps:
            - name: Downloadig the artifacts
              uses: actions/download-artifact@v4
              with:
                name: drop
                repository: ${{github.repository}}
                run-id: 13114236398
                github-token: ${{github.token}}

            - name: Deploy to nginx
              run: |
                sudo rm -rf /usr/share/nginx/html/*
                sudo cp /home/ec2-user/actions-runner/_work/Angular_app/Angular_app/my_app/browser/* /usr/share/nginx/html
                sudo systemctl restart nginx